### ISSUE TITLE
The images cannot be moved.

### ISSUE THREAD

**Issue by rich-pel** [ThomasKlein18/asparagus#2]
Probably the files are not completly written before they are moved.

**Comment by ThomasKlein18** [comment]
I don't understand the problem. Are you referring to the raw images in the raw_data folder? Do you mean that you cannot move them to a different location? Sounds like a Windows issue if so

**Comment by rich-pel** [comment]
Bug is fixed. Service is working.

**Comment by luananama** [comment]
solved.
